---
title: "Data Manipulation"
author: "Kristal Quispe"
date: "9/26/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

## Import datasets
```{r}
litters_data = read_csv("./data/FAS_litters.csv")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv")
pups_data = janitor::clean_names(pups_data)
```


## Selecting!!!

```{r}
select(litters_data, group, litter_number)

select(litters_data, group, litter_number, gd0_weight)

select(litters_data, litter_number, gd0_weight, starts_with("pups"))

select(litters_data, litter_number, group, gd0_weight)

select(litters_data, litter_number, group, everything())

## Here if you had selected just the helper everything function you would still get all the same variables in the output but you woudnt have it in the order with litter number firt, group second, followed by everything else. 

select(litters_data, -group)

select(litters_data, litter_number, gd0_weight:pups_born_alive)

litters_selected = select(litters_data, litter_number, gd0_weight:pups_born_alive)

select(litters_data, GROUP = group, litter_number)

rename(litters_data, GROUP = group)

```

## Filtering!!!!

```{r}
filter(litters_data, group == "Con7")

## one = would assign group to Con7, and two == asks is group equal to Con7

filter(litters_data,gd_of_birth == 20 )

filter(litters_data, gd_of_birth < 20)

filter(litters_data, gd_of_birth >= 20)

filter(litters_data, pups_born_alive < 6)

filter(litters_data, pups_born_alive < 6, group == "Con7" )

# != means does not equal. for multiple conditions you can use a comma or a and sign &

filter(litters_data, group == "Con7" | group == "Mod8")

filter(litters_data, group %in% c("Con7", "Con8"))

# | is the OR Statement, and is the same as the IN statement

filter(litters_data, pups_born_alive >= 4, pups_born_alive <=6)
# R isnt good at ranges so use a less than and greater than part to get at a range

filter(litters_data, gd0_weight + gd18_weight < 70)

filter(litters_data, gd0_weight > gd18_weight)

filter(litters_data, is.na(gd0_weight))


filter(litters_data, !is.na(gd0_weight))
# Dont do the !is.na code to get data without missing values. 

drop_na(litters_data)
#This will only give me complete cases

drop_na(litters_data, gd0_weight)
#Will only drop rows where gd0_weight is NA, but not where any other variable is NA


```


## Mutate

```{r}

#Mutate is to create new variables and edit variables
mutate(litters_data, wt_gain = gd18_weight - gd0_weight)

mutate(
  litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group))

mutate(
  litters_data, 
  wt_gain = gd18_weight - gd0_weight,
  group = str_to_lower(group),
  group = str_to_upper(group))

```

Mutating is great ... but I don't have more examples. 

## Arrange

```{r}
arrange(litters_data, pups_born_alive)
#Put dataset in order of the number of pups born alive.  

arrange(litters_data, desc(pups_born_alive))
#Opposite ordering

arrange(litters_data, pups_born_alive, gd0_weight)
#Arrange on pup_born alive in ascending order (default), and then order by weight at gd0.
```


## pipe...

Create a collection of commands...



```{r}

```

